###
# Server configurations
###
server:
  port: 8080

###
# Logging configurations
###
logging:
  level:
    root: info
    org.springframework: info
    com.example.es: trace

###
# Spring configurations
###
spring:
  ###
  # Application name
  ###
  application:
    name: elastic-search

  ###
  # ElasticSearch - Configurations
  ###
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
      repositories:
        enabled: true

#elasticsearch:
#  clustername: elasticsearch
#  host: localhost
#  port: 9300
