server:
  port: 8080

spring:
  application:
    name: elastic-search

  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
      repositories:
        enabled: true

#elasticsearch:
#  clustername: elasticsearch
#  host: localhost
#  port: 9300